{% set name = "csdms-pydeltarcm" %}
{% set version = "0.1" %}
{% set build_string = environ.get('GIT_BUILD_STR', '') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mperignon/pyDeltaRCM_WMT

requirements:
  build:
    - bmi-babel
    - pydeltarcm
  run:
    - bmi-babel
    - pydeltarcm

test:
  requires:
    - pymt
    - bmi-tester
